// All the movie data for the "Now Showing" page with day-specific showtimes
const MOVIES = [
  {
    id: 'interstellar',
    title: 'Interstellar',
    genre: 'scifi',
    genreLabel: 'Sci-Fi / Drama',
    rating: '12A',
    runtime: 169,
    showtimes: {
      mon: ['14:00', '18:30'],
      tue: ['14:00', '18:30'],
      wed: ['14:00', '18:30'],
      thu: ['14:00', '18:30'],
      fri: ['14:00', '18:30', '22:45'],
      sat: ['11:00', '14:00', '18:30', '22:45'],
      sun: ['11:00', '14:00', '18:30'],
    },
    screen: 1,
    image: 'images/interstellar.jpg',
    alt: 'Interstellar poster',
    description:
      "When Earth becomes uninhabitable, a team of explorers led by former NASA pilot Cooper embarks on humanity's most important mission: traveling through a newly discovered wormhole near Saturn to find a new home for mankind. As the crew ventures into unknown galaxies, they confront the mysteries of space-time, black holes, and the crushing weight of relativity—where hours become years. Christopher Nolan's epic masterpiece explores themes of love, sacrifice, and survival across the cosmos, featuring stunning visual effects and an unforgettable score by Hans Zimmer.",
  },
  {
    id: 'the-shining',
    title: 'The Shining',
    genre: 'horror',
    genreLabel: 'Horror',
    rating: '18',
    runtime: 146,
    showtimes: {
      mon: ['20:45'],
      tue: ['20:45'],
      wed: ['20:45'],
      thu: ['20:45', '23:15'],
      fri: ['20:45', '23:15'],
      sat: ['20:45', '23:15'],
      sun: ['20:45'],
    },
    screen: 2,
    image: 'images/the-shining.jpg',
    alt: 'The Shining poster',
    description:
      "Jack Torrance accepts a position as off-season caretaker at the isolated Overlook Hotel in the Colorado Rockies, bringing his wife Wendy and psychic son Danny along for the winter. As Jack struggles with writer's block and the eerie emptiness of the hotel, the dark supernatural forces lurking within its walls begin to take hold of his sanity. Stanley Kubrick's legendary adaptation of Stephen King's novel is a masterclass in psychological horror, featuring iconic performances, unsettling cinematography, and some of the most terrifying scenes in cinema history.",
  },
  {
    id: 'scream-1996',
    title: 'Scream (1996)',
    genre: 'horror',
    genreLabel: 'Horror',
    rating: '18',
    runtime: 111,
    showtimes: {
      mon: ['21:15'],
      tue: ['21:15'],
      wed: ['21:15'],
      thu: ['21:15', '23:30'],
      fri: ['21:15', '23:30'],
      sat: ['17:45', '21:15', '23:30'],
      sun: ['21:15'],
    },
    screen: 3,
    image: 'images/scream-1996.jpg',
    alt: 'Scream 1996 poster',
    description:
      "A year after the tragic murder of Sidney Prescott's mother, a masked killer named Ghostface begins terrorizing the small town of Woodsboro, targeting Sidney and her friends. As bodies pile up, the teens realize they're trapped in a real-life horror movie—and knowing the rules of slasher films might be their only chance at survival. Wes Craven's genre-defining thriller revitalized horror with its clever meta-commentary, sharp wit, and genuinely shocking twists. Featuring an incredible ensemble cast led by Neve Campbell, this film reminds us that everyone is a suspect.",
  },
  {
    id: 'collateral',
    title: 'Collateral',
    genre: 'drama',
    genreLabel: 'Thriller',
    rating: '15',
    runtime: 120,
    showtimes: {
      mon: ['16:30', '20:00'],
      tue: ['16:30', '20:00'],
      wed: ['16:30', '20:00'],
      thu: ['16:30', '20:00'],
      fri: ['16:30', '20:00'],
      sat: ['13:45', '16:30', '20:00'],
      sun: ['13:45', '16:30', '20:00'],
    },
    screen: 4,
    image: 'images/collateral.jpg',
    alt: 'Collateral poster',
    description:
      "Max is a Los Angeles cab driver with dreams of starting his own limousine business, but his carefully ordered world is shattered when he picks up Vincent—a slick, silver-haired hitman with a list of targets to eliminate before dawn. Held hostage in his own taxi, Max is forced to navigate the neon-lit streets of LA as Vincent executes his deadly assignments with chilling precision. Michael Mann's atmospheric neo-noir thriller features powerhouse performances from Jamie Foxx and Tom Cruise, capturing the tension and moral complexity of one fateful night in the city of angels.",
  },
  {
    id: 'the-dark-knight',
    title: 'The Dark Knight',
    genre: 'drama',
    genreLabel: 'Action / Crime',
    rating: '12A',
    runtime: 152,
    showtimes: {
      mon: ['15:45', '19:30'],
      tue: ['15:45', '19:30'],
      wed: ['15:45', '19:30'],
      thu: ['15:45', '19:30'],
      fri: ['12:30', '15:45', '19:30'],
      sat: ['12:30', '15:45', '19:30', '23:00'],
      sun: ['12:30', '15:45', '19:30'],
    },
    screen: 5,
    image: 'images/the-dark-knight.jpg',
    alt: 'The Dark Knight poster',
    description:
      "Batman has succeeded in driving organized crime from Gotham City with the help of District Attorney Harvey Dent and Lieutenant James Gordon. But the arrival of a criminal mastermind known only as the Joker throws the city into chaos, forcing Batman to confront the thin line between heroism and vigilantism. Heath Ledger delivers an Oscar-winning performance as the anarchic Joker in Christopher Nolan's groundbreaking superhero epic—a film that transcends its genre with philosophical depth, moral complexity, and breathtaking action sequences. This is cinema at its finest.",
  },
  {
    id: 'heretic',
    title: 'Heretic',
    genre: 'horror',
    genreLabel: 'Horror',
    rating: '18',
    runtime: 100,
    showtimes: {
      mon: ['22:30'],
      tue: ['22:30'],
      wed: ['22:30'],
      thu: ['22:30'],
      fri: ['19:45', '22:30'],
      sat: ['19:45', '22:30'],
      sun: ['19:45', '22:30'],
    },
    screen: 6,
    image: 'images/heretic.jpg',
    alt: 'Heretic poster',
    description:
      'In a remote community bound by ancient traditions and religious fervor, two young missionaries knock on the wrong door and find themselves trapped in a theological nightmare. What begins as a philosophical discussion about faith and doubt descends into a horrifying test of belief as their charismatic host reveals his true intentions. This unsettling psychological horror explores the darkest corners of religious obsession, featuring intense performances and a suffocating atmosphere of dread. Prepare for a thought-provoking journey into the nature of faith itself—and the terror that lies beyond its boundaries.',
  },
  {
    id: 'halloween-1978',
    title: 'Halloween (1978)',
    genre: 'horror',
    genreLabel: 'Horror',
    rating: '18',
    runtime: 91,
    showtimes: {
      mon: ['23:45'],
      tue: ['23:45'],
      wed: ['23:45'],
      thu: ['23:45'],
      fri: ['21:00', '23:45'],
      sat: ['21:00', '23:45'],
      sun: ['21:00', '23:45'],
    },
    screen: 7,
    image: 'images/halloween-1978.jpg',
    alt: 'Halloween 1978 poster',
    description:
      "Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a psychiatric hospital and returns to the quiet town of Haddonfield, Illinois. As his psychiatrist Dr. Loomis desperately tries to track him down, Michael begins stalking teenager Laurie Strode and her friends on Halloween night. John Carpenter's landmark slasher film established countless horror conventions and launched one of cinema's most iconic villains. With its minimalist synth score, steady-cam stalking sequences, and Jamie Lee Curtis's star-making performance, Halloween remains the gold standard of terror.",
  },
  {
    id: 'heat',
    title: 'Heat',
    genre: 'drama',
    genreLabel: 'Crime / Drama',
    rating: '15',
    runtime: 170,
    showtimes: {
      mon: ['17:15'],
      tue: ['17:15'],
      wed: ['17:15'],
      thu: ['17:15'],
      fri: ['13:30', '17:15', '21:00'],
      sat: ['10:30', '13:30', '17:15', '21:00'],
      sun: ['10:30', '13:30', '17:15'],
    },
    screen: 8,
    image: 'images/heat.jpg',
    alt: 'Heat poster',
    description:
      "Neil McCauley leads a tight crew of professional thieves through meticulously planned heists across Los Angeles, living by the code that he must be able to walk away from everything in 30 seconds flat. LAPD Lieutenant Vincent Hanna is equally obsessed with his work, sacrificing his personal life to hunt down McCauley's crew. As these two masters of their crafts circle each other, Michael Mann crafts an operatic crime epic featuring the legendary face-off between Al Pacino and Robert De Niro. With its philosophical depth, stunning action sequences, and exploration of masculinity and obsession, Heat stands as one of the greatest crime films ever made.",
  },
  {
    id: 'the-iron-claw',
    title: 'The Iron Claw',
    genre: 'drama',
    genreLabel: 'Drama / Biopic',
    rating: '15',
    runtime: 132,
    showtimes: {
      mon: ['14:30', '18:45'],
      tue: ['14:30', '18:45'],
      wed: ['14:30', '18:45'],
      thu: ['14:30', '18:45'],
      fri: ['14:30', '18:45'],
      sat: ['11:30', '14:30', '18:45'],
      sun: ['11:30', '14:30', '18:45'],
    },
    screen: 1,
    image: 'images/iron-claw.jpg',
    alt: 'The Iron Claw poster',
    description:
      "The Von Erich family dominated professional wrestling in the 1980s, with patriarch Fritz pushing his sons to achieve the greatness that eluded him. But behind the spotlight and championship belts lay a darker story of pressure, tragedy, and a curse that seemed to haunt the family. This powerful biographical drama chronicles the rise and heartbreaking fall of wrestling's most legendary dynasty, featuring incredible performances led by Zac Efron as Kevin Von Erich. A raw, emotional exploration of family, masculinity, fame, and the devastating cost of chasing an impossible dream.",
  },
  {
    id: 'mission-impossible-fallout',
    title: 'Mission: Impossible – Fallout',
    genre: 'drama',
    genreLabel: 'Action / Spy',
    rating: '12A',
    runtime: 147,
    showtimes: {
      mon: ['13:15', '19:00'],
      tue: ['13:15', '19:00'],
      wed: ['13:15', '19:00'],
      thu: ['13:15', '19:00'],
      fri: ['13:15', '16:15', '19:00'],
      sat: ['10:15', '13:15', '16:15', '19:00'],
      sun: ['10:15', '13:15', '16:15', '19:00'],
    },
    screen: 2,
    image: 'images/mission-impossible-fallout.jpg',
    alt: 'Mission Impossible Fallout poster',
    description:
      "When an IMF mission to intercept stolen plutonium goes catastrophically wrong, Ethan Hunt and his team find themselves racing against time to prevent nuclear devastation. As the CIA questions Hunt's judgment and assigns Agent August Walker to monitor him, Ethan must navigate a web of betrayal while confronting the consequences of his past decisions. Tom Cruise delivers another death-defying performance in this pulse-pounding thriller, featuring jaw-dropping practical stunts including a HALO jump and a helicopter chase over New Zealand. Christopher McQuarrie directs this intense, emotionally resonant entry that proves why Mission: Impossible remains the gold standard of action cinema.",
  },
  {
    id: 'no-country-for-old-men',
    title: 'No Country for Old Men',
    genre: 'drama',
    genreLabel: 'Thriller / Crime',
    rating: '15',
    runtime: 122,
    showtimes: {
      mon: ['17:00', '20:30'],
      tue: ['17:00', '20:30'],
      wed: ['17:00', '20:30'],
      thu: ['17:00', '20:30'],
      fri: ['17:00', '20:30'],
      sat: ['14:15', '17:00', '20:30'],
      sun: ['14:15', '17:00', '20:30'],
    },
    screen: 3,
    image: 'images/no-country-for-old-men.jpg',
    alt: 'No Country for Old Men poster',
    description:
      "While hunting antelope near the Rio Grande in 1980, Vietnam veteran Llewelyn Moss stumbles upon the aftermath of a drug deal gone wrong—and a suitcase containing two million dollars. His decision to take the money sets off a cat-and-mouse chase with Anton Chigurh, a remorseless killer who determines his victims' fates with the flip of a coin. The Coen Brothers' masterpiece adaptation of Cormac McCarthy's novel is a haunting meditation on fate, morality, and the unstoppable march of violence. Javier Bardem's Oscar-winning performance as Chigurh creates one of cinema's most terrifying villains.",
  },
  {
    id: '2001-a-space-odyssey',
    title: '2001: A Space Odyssey',
    genre: 'scifi',
    genreLabel: 'Sci-Fi',
    rating: 'PG',
    runtime: 149,
    showtimes: {
      mon: ['15:00'],
      tue: ['15:00'],
      wed: ['15:00'],
      thu: ['15:00'],
      fri: ['11:45', '15:00', '18:15'],
      sat: ['11:45', '15:00', '18:15'],
      sun: ['11:45', '15:00', '18:15'],
    },
    screen: 4,
    image: 'images/2001-space-odyssey.jpg',
    alt: '2001: A Space Odyssey poster',
    description:
      'From the dawn of man to the infinite reaches of space, Stanley Kubrick\'s visionary masterpiece follows humanity\'s evolution guided by mysterious black monoliths. When astronauts discover another monolith buried on the moon, they embark on a mission to Jupiter aboard the spacecraft Discovery One, accompanied by the AI system HAL 9000. What unfolds is a transcendent journey through space and time that challenges our understanding of existence itself. With groundbreaking special effects that still astound today, minimal dialogue, and the iconic soundtrack featuring "The Blue Danube" and "Also sprach Zarathustra," 2001 remains the ultimate cinematic odyssey—a philosophical and visual experience unlike any other.',
  },
  {
    id: 'goodfellas',
    title: 'Goodfellas',
    genre: 'drama',
    genreLabel: 'Crime / Drama',
    rating: '18',
    runtime: 146,
    showtimes: {
      mon: ['18:15'],
      tue: ['18:15'],
      wed: ['18:15'],
      thu: ['18:15'],
      fri: ['15:00', '18:15', '21:30'],
      sat: ['15:00', '18:15', '21:30'],
      sun: ['15:00', '18:15'],
    },
    screen: 5,
    image: 'images/goodfellas.jpg',
    alt: 'Goodfellas poster',
    description:
      "From his childhood in Brooklyn, Henry Hill dreamed of being a gangster. As a young man, he works his way up through the ranks of a local mob crew with his partners Jimmy Conway and Tommy DeVito, living a life of luxury funded by robbery, extortion, and murder. But as Henry becomes increasingly entangled in the world of drugs and FBI investigations, the lifestyle he idolized begins to unravel. Martin Scorsese's electrifying crime saga, based on the true story of Henry Hill, revolutionized the gangster genre with its frenetic energy, dark humor, and unforgettable performances from Ray Liotta, Robert De Niro, and Joe Pesci.",
  },
  {
    id: 'edge-of-tomorrow',
    title: 'Edge of Tomorrow',
    genre: 'scifi',
    genreLabel: 'Sci-Fi / Action',
    rating: '12A',
    runtime: 113,
    showtimes: {
      mon: ['12:45', '17:30'],
      tue: ['12:45', '17:30'],
      wed: ['12:45', '17:30'],
      thu: ['12:45', '17:30'],
      fri: ['12:45', '15:30', '17:30', '20:15'],
      sat: ['10:00', '12:45', '15:30', '17:30', '20:15'],
      sun: ['10:00', '12:45', '15:30', '17:30'],
    },
    screen: 6,
    image: 'images/edge-of-tomorrow.jpg',
    alt: 'Edge of Tomorrow poster',
    description:
      'Major William Cage, a military PR officer with no combat experience, is thrust into a suicide mission against an alien invasion that has devastated Europe. Killed within minutes, Cage finds himself inexplicably caught in a time loop—forced to relive the same brutal battle over and over. With each reset, he teams up with war hero Rita Vrataski to improve his skills and uncover a way to defeat the seemingly invincible alien force. Tom Cruise and Emily Blunt star in this innovative sci-fi thriller that combines Groundhog Day with intense action, creating a propulsive, endlessly entertaining ride that gets better with each loop.',
  },
  {
    id: 'pulp-fiction',
    title: 'Pulp Fiction',
    genre: 'drama',
    genreLabel: 'Crime / Drama',
    rating: '18',
    runtime: 154,
    showtimes: {
      mon: ['19:15'],
      tue: ['19:15'],
      wed: ['19:15'],
      thu: ['19:15'],
      fri: ['16:00', '19:15'],
      sat: ['13:00', '16:00', '19:15'],
      sun: ['13:00', '16:00', '19:15'],
    },
    screen: 7,
    image: 'images/pulp-fiction.jpg',
    alt: 'Pulp Fiction poster',
    description:
      "In a series of interwoven Los Angeles crime stories told out of chronological order, hitmen Vincent Vega and Jules Winnfield philosophize about foot massages and divine intervention between assignments; boxer Butch Coolidge double-crosses his mob boss; and Vincent must escort his boss's wife Mia on a night out that goes dangerously wrong. Quentin Tarantino's groundbreaking second film revolutionized independent cinema with its sharp dialogue, eclectic soundtrack, and nonlinear narrative. Featuring iconic performances from John Travolta, Uma Thurman, and Samuel L. Jackson, Pulp Fiction remains one of the most influential and endlessly quotable films ever made.",
  },
  {
    id: 'fight-club',
    title: 'Fight Club',
    genre: 'drama',
    genreLabel: 'Drama',
    rating: '18',
    runtime: 139,
    showtimes: {
      mon: ['21:45'],
      tue: ['21:45'],
      wed: ['21:45'],
      thu: ['21:45'],
      fri: ['18:30', '21:45'],
      sat: ['18:30', '21:45'],
      sun: ['18:30', '21:45'],
    },
    screen: 8,
    image: 'images/fight-club.jpg',
    alt: 'Fight Club poster',
    description:
      "An unnamed narrator suffering from chronic insomnia and consumer culture malaise finds temporary relief in support groups for diseases he doesn't have. His carefully constructed life is disrupted when he meets Tyler Durden, a charismatic soap salesman with a very different philosophy on life. Together, they form an underground fight club that evolves into something far more sinister—a nationwide anarchist organization called Project Mayhem. David Fincher's explosive adaptation of Chuck Palahniuk's novel is a savage critique of masculinity and consumerism, featuring career-defining performances from Edward Norton and Brad Pitt. A mind-bending thriller that demands multiple viewings.",
  },
  {
    id: 'one-flew-over-the-cuckoos-nest',
    title: "One Flew Over the Cuckoo's Nest",
    genre: 'drama',
    genreLabel: 'Drama',
    rating: '15',
    runtime: 133,
    showtimes: {
      mon: ['15:30'],
      tue: ['15:30'],
      wed: ['15:30'],
      thu: ['15:30', '18:45'],
      fri: ['15:30', '18:45'],
      sat: ['12:15', '15:30', '18:45'],
      sun: ['12:15', '15:30', '18:45'],
    },
    screen: 1,
    image: 'images/one-flew-over-the-cuckoos-nest.jpg',
    alt: "One Flew Over the Cuckoo's Nest poster",
    description:
      'Randle McMurphy, a free-spirited convict, fakes insanity to serve his sentence in a mental institution rather than prison. But the psychiatric ward he enters is ruled with an iron fist by Nurse Ratched, whose calm demeanor masks a cruel determination to break the spirits of her patients. As McMurphy challenges her authority and brings life back to the ward, he sparks a revolution—but at what cost? Miloš Forman\'s landmark film swept the "Big Five" Oscars with Jack Nicholson delivering one of cinema\'s most iconic performances. A powerful exploration of freedom, conformity, and the human spirit that remains devastatingly relevant.',
  },
  {
    id: 'the-silence-of-the-lambs',
    title: 'The Silence of the Lambs',
    genre: 'drama',
    genreLabel: 'Thriller',
    rating: '18',
    runtime: 118,
    showtimes: {
      mon: ['18:45'],
      tue: ['18:45'],
      wed: ['18:45'],
      thu: ['18:45', '21:45'],
      fri: ['18:45', '21:45'],
      sat: ['16:00', '18:45', '21:45'],
      sun: ['16:00', '18:45'],
    },
    screen: 2,
    image: 'images/silence-of-the-lambs.jpg',
    alt: 'The Silence of the Lambs poster',
    description:
      "FBI trainee Clarice Starling is pulled from her studies by Jack Crawford to interview Dr. Hannibal Lecter—a brilliant psychiatrist and cannibalistic serial killer. The FBI hopes Lecter can provide insight into another serial killer known as Buffalo Bill, who is kidnapping and murdering young women. As Clarice matches wits with the sophisticated monster, a dangerous psychological game unfolds. Jonathan Demme's masterful thriller features Oscar-winning performances from Jodie Foster and Anthony Hopkins, whose chilling portrayal of Hannibal Lecter has become one of cinema's most iconic villains. A cat-and-mouse thriller that keeps you on edge until the final frame.",
  },
  {
    id: 'the-green-mile',
    title: 'The Green Mile',
    genre: 'drama',
    genreLabel: 'Drama / Fantasy',
    rating: '15',
    runtime: 189,
    showtimes: {
      mon: ['13:00'],
      tue: ['13:00'],
      wed: ['13:00'],
      thu: ['13:00', '17:30'],
      fri: ['13:00', '17:30'],
      sat: ['10:45', '13:00', '17:30'],
      sun: ['10:45', '13:00', '17:30'],
    },
    screen: 3,
    image: 'images/the-green-mile.jpg',
    alt: 'The Green Mile poster',
    description:
      "In 1935, Paul Edgecomb is head guard on death row at Cold Mountain Penitentiary, where inmates walk \"the green mile\" to their execution. When John Coffey, a massive man convicted of murdering two young girls, arrives on the block, Paul discovers this gentle giant possesses a miraculous supernatural gift. As Paul witnesses Coffey's healing powers and gentle nature, he begins to question everything about justice, mercy, and faith. Frank Darabont's epic adaptation of Stephen King's novel features an unforgettable performance by Michael Clarke Duncan and explores profound themes of innocence, redemption, and the presence of miracles in the darkest places.",
  },
  {
    id: 'the-departed',
    title: 'The Departed',
    genre: 'drama',
    genreLabel: 'Crime / Thriller',
    rating: '18',
    runtime: 151,
    showtimes: {
      mon: ['19:30'],
      tue: ['19:30'],
      wed: ['19:30'],
      thu: ['16:15', '19:30'],
      fri: ['16:15', '19:30'],
      sat: ['13:15', '16:15', '19:30'],
      sun: ['13:15', '16:15', '19:30'],
    },
    screen: 4,
    image: 'images/the-departed.jpg',
    alt: 'The Departed poster',
    description:
      "In South Boston, the Massachusetts State Police are waging war on Irish-American organized crime boss Frank Costello. Young undercover cop Billy Costigan infiltrates Costello's inner circle while simultaneously, criminal Colin Sullivan has infiltrated the police department as Costello's mole. As both organizations realize they have a rat in their midst, Billy and Colin find themselves in a deadly game to identify the other before being discovered themselves. Martin Scorsese finally won his long-overdue Best Director Oscar for this intense crime thriller featuring an all-star ensemble including Leonardo DiCaprio, Matt Damon, Jack Nicholson, and Mark Wahlberg in career-best performances.",
  },
];
// this Make MOVIES available globally
window.MOVIES = MOVIES;
